package de.testswing;


import javax.swing.*;

/* This program takes as input the AFP file name and provides with user the PDF for the same */

public class Deepafile extends javax.swing.JFrame {

	
	// Variables declaration - do not modify  
	
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;    
    private javax.swing.JLabel jLabel5;    
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    
    // End of variables declaration            
    
    /**
     * Creates new form MainWindow
     */
    public Deepafile () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();              /* Input Type  */
        jComboBox1 = new javax.swing.JComboBox();      
        jLabel2 = new javax.swing.JLabel();              /* Input Value */
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();              /* User Name   */
        jTextField2 = new javax.swing.JTextField();        
        jLabel4 = new javax.swing.JLabel();              /* Password    */
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();              /* Email id    */
        jTextField4 = new javax.swing.JTextField();

        jButton1 = new javax.swing.JButton();            /* Copy to IMSE */
        jButton2 = new javax.swing.JButton();            /* Get PDF      */
        jButton3 = new javax.swing.JButton();            /* Cancel       */

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        /* Input Type */
        jLabel1.setText("Input Type");
        jLabel1.setName("lbltype"); 
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UUID", "Filenet Id", "AFP File" }));
        jComboBox1.setName("cmbInptype");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        /* Input type's Value */        
        jLabel2.setText("Value");
        jLabel2.setName("lblInpvalue"); 
        jTextField1.setName("txtInpvalue"); 
        
        /* Username Value */        
        jLabel2.setText("Value");
        jLabel2.setName("lblUsername"); 
        jTextField1.setName("txtUsername");
        
        /* Host Password      */        
        jLabel3.setText("Username");
        jLabel3.setName("lblUsername"); 
        jTextField2.setName("txtUsername");
        
        /* Password          */        
        jLabel4.setText("Password");
        jLabel4.setName("lblPassword"); 
        jTextField3.setName("txtPassword");
        
        
        /* Email id          */        
        jLabel5.setText("Email Id");
        jLabel5.setName("lblEmailid"); 
        jTextField4.setName("txtEmailid");
        

        
        jButton1.setText("Copy to IMSE");
        jButton1.setName("btncopy"); 
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Get PDF");
        jButton2.setName("btngetpdf"); 
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.setName("btncancel"); 
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)                            
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)                            
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)                            
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)                            
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    

                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:

            
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String inpType,fid;
        inpType = (String)(jComboBox1.getSelectedItem());
        if (inpType == "Filenet Id")
        {
            System.out.println("Ok input");
            fid = jTextField1.getText();
            System.out.println("Input fid=" + fid);
//            APKVDocumentDAOImpl_Filenet fobj = new APKVDocumentDAOImpl_Filenet();
//            fobj.getDBConnection();
//            fobj.insertTBCOAntragDaten(fid);
        }
        else
        {
            System.out.println("Not ok input");
            JOptionPane.showMessageDialog(null, "Please select Filenet Id as input !");
        }          
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { 
		System.out.println("Get PDF clicked !");
        String inptype,inpval,user,pwd,email,errmsg;
        inptype = (String)(jComboBox1.getSelectedItem());
        inpval  = jTextField1.getText();
        user    = jTextField2.getText();
        pwd     = jTextField3.getText();
        email   = jTextField4.getText();   
        errmsg  = null;
        if (inptype == "AFP File")
        {      	
        	if (inpval.length() > 0 && user.length() > 0 && pwd.length() > 0 && email.length() > 0)
        	{
        		System.out.println("Inputs are ok !");
        	}
        	else
        	{
                if (email.length() == 0)  errmsg = "Please enter your email address !";
                if (pwd.length() == 0)    errmsg = "Please enter your host password !";                
                if (user.length() == 0)   errmsg = "Please enter your host userid !";
                if (inpval.length() == 0) errmsg = "Please enter a valid host dataset name !";
                JOptionPane.showMessageDialog(null, errmsg);                
        	}
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
    }   
    
    
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deepafile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deepafile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deepafile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deepafile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deepafile().setVisible(true);
            }
        });
    }
	
       
}
